### ISSUE TITLE
Option 2: Adding the Widget as a Node Module

### ISSUE THREAD

**Issue by zombo99** [pingidentity/pf-authn-js-widget#102]
**Describe the bug**
failure on install into existing node project, node 16.3.1.

**To Reproduce**
1. cd <to package.json folder>;
2. npm install @ping-identity/pf-authn-js-widget --save
3. returns -
--
...
69 silly fetch manifest yargs-parser@^18.1.2
70 http fetch GET 200 https://registry.npmjs.org/y18n 32ms (cache miss)
71 http fetch GET 200 https://registry.npmjs.org/cliui 39ms (cache miss)
72 http fetch GET 200 https://registry.npmjs.org/yargs-parser 49ms (cache miss)
73 timing idealTree:node_modules/qrcode Completed in 62ms
74 timing idealTree:node_modules/dijkstrajs Completed in 0ms
75 timing idealTree:node_modules/encode-utf8 Completed in 0ms
76 timing idealTree:node_modules/pngjs Completed in 0ms
77 silly placeDep ROOT strict-uri-encode@1.1.0 OK for: query-string@5.1.1 want: ^1.0.0
78 timing idealTree:node_modules/query-string Completed in 3ms
79 timing idealTree:node_modules/strict-uri-encode Completed in 0ms
80 timing idealTree:node_modules/validate.js Completed in 0ms
81 timing idealTree:node_modules/whatwg-fetch Completed in 0ms
82 silly placeDep node_modules/qrcode cliui@6.0.0 OK for: yargs@15.4.1 want: ^6.0.0
83 silly placeDep node_modules/qrcode y18n@4.0.3 OK for: yargs@15.4.1 want: ^4.0.0
84 timing idealTree Completed in 3023ms
85 timing command:install Completed in 3069ms
86 notice New minor version of npm available! 8.1.2 -> 8.6.0
86 notice Changelog: <https://github.com/npm/cli/releases/tag/v8.6.0>
86 notice Run `npm install -g npm@8.6.0` to update!
87 verbose stack TypeError: Invalid Version: ~18.1.2
87 verbose stack     at new SemVer (D:\nodejs\node_modules\npm\node_modules\semver\classes\semver.js:38:13)
87 verbose stack     at compare (D:\nodejs\node_modules\npm\node_modules\semver\functions\compare.js:3:32)
87 verbose stack     at Object.gte (D:\nodejs\node_modules\npm\node_modules\semver\functions\gte.js:2:30)
87 verbose stack     at CanPlaceDep.checkCanPlaceCurrent (D:\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\can-place-dep.js:173:51)
87 verbose stack     at CanPlaceDep.checkCanPlace (D:\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\can-place-dep.js:157:27)
87 verbose stack     at new CanPlaceDep (D:\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\can-place-dep.js:114:26)
87 verbose stack     at PlaceDep.place (D:\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\place-dep.js:121:19)
87 verbose stack     at new PlaceDep (D:\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\place-dep.js:71:10)
87 verbose stack     at D:\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:944:31
87 verbose stack     at Array.map (<anonymous>)
88 verbose cwd D:\rabbit_holes\UX\_current\FrontEnd
89 verbose Windows_NT 10.0.19044
90 verbose argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "@ping-identity/pf-authn-js-widget" "--save"
91 verbose node v16.13.1
92 verbose npm  v8.1.2
93 error Invalid Version: ~18.1.2

**Comment by mketchum** [comment]
We are unable to reproduce this. Our testing on windows was with node v16.15.0 and npm v8.5.5.
