### ISSUE TITLE
Widget needs to support P1 Protect as a Captcha Provider

### ISSUE THREAD

**Issue by cprice-ping** [pingidentity/pf-authn-js-widget#130]
**Describe the bug**
Documentation currently assumes that only Google Captcha is available, but P1 Protect also delivers a Provider. The instructions in the repo do not account for this, nor is it clear that P1 Protect works at all when the Provider is configured.

**To Reproduce**
1. Install P1 Protect IK
2. Configure Risk Provider
3. Enable on HTML Form
4. Launch the Widget
5. Attempt to logon

**Expected behavior**
P1 Protect needs to be fully supported by the Widget, with clear instructions on how to include it with your app integration

**Screenshots**
![image](https://github.com/pingidentity/pf-authn-js-widget/assets/43251598/4786204b-7ba9-45dc-a43b-00a21b85e075)

**Desktop (please complete the following information):**
MacOS Ventura \ Safari

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by jkhosravian-ping** [comment]
This issue is resolved in the latest release
