### ISSUE TITLE
Update README navigation instructions for new UI locations

### ISSUE THREAD

**Issue by brucem-ping** [pingidentity/pf-authn-js-widget#31]
**Describe the bug**
The navigation steps specified for the PingFederate admin UI have not been updated to match the new UI layout.

**To Reproduce**
In the [pingfederate configuration section of the README](https://github.com/pingidentity/pf-authn-js-widget#pingfederate-configuration) the old  UI navigation steps of "Identity Provider > Authentication Applications > Enable Authentication API" are specified.

**Expected behavior**
The new UI navigation steps should be specified  as "Authentication > Integration > Authentication API Applications".

**Additional context**
There may be other places that need to be updated for the new UI, but this is the only one I've noticed.

**Comment by philipcoldrey-ping** [comment]
Fixed with pull request #32
