### ISSUE TITLE
Include a Screenshot of the Default Widget in the Project README

### ISSUE THREAD

**Issue by BruceMacD** [pingidentity/pf-authn-js-widget#4]
**Problem Description**
In order to get a high-level overview of the widget I need to read the whole README then download and run the project.

**Expected Functionality**
Screenshots of the default widget configuration in the README would visually communicate the functionality of the project.

**Workarounds**
Downloading the project and running it.

**Comment by philipcoldrey-ping** [comment]
Thanks for this suggestion. A screenshot has been added to the readme as you requested. We may enhance this further in the future but for now I am closing this issue as resolved.
