### ISSUE TITLE
After putting username and password it shows flowid is required

### ISSUE THREAD

**Issue by mechnixlab** [pingidentity/pf-authn-js-widget#48]
Getting flowId is required after putting the valid username and password
![image](https://user-images.githubusercontent.com/54431232/105879616-99cb5800-602c-11eb-9373-f45f78a08a7b.png)

**Comment by mketchum** [comment]
Hmm, that looks odd. Can you describe a little bit more about what sort of setup inside PingFederate the widget is using? It looks like something is returning is redirecting you back to the widget with a code and state parameter, rather than redirecting the browser back to PingFederate.
