### ISSUE TITLE
`index.html` is incorrect in your README

### ISSUE THREAD

**Issue by rlyleping** [pingidentity/pf-authn-js-widget#5]
**Describe the bug**
You're missing the logo tag in `index.html` and thus you get a broken image when outside of the node server setup.

**To Reproduce**
Follow your current instructions

**Expected behavior**
Should see Ping logo out of the box

**Additional context**
`index.html` should contain the following line:
<script>
      function load() {
        var authnWidget = new PfAuthnWidget("https://{{baseURL}}:9031", { divId: 'authnwidget' , logo: 'assets/ping-logo.svg'});
        authnWidget.init()
      }
      window.onload = load;
    </script>

**Comment by philipcoldrey-ping** [comment]
Thanks for raising this issue. We'll investigate and update this issue with our progress.
