### ISSUE TITLE
Readable code

### ISSUE THREAD

**Issue by trijohn** [pingidentity/pf-authn-js-widget#52]
Hello, I am looking to see if there is another version of the JavaScript that is more readable? I would like the opportunity to extend as i need rather than submit a feature request and hope and wait it is included.  for instance, currently the one time password is not supported with the widget. 
The widget is pretty awesome, I just am looking to be able to add to it as needed and am looking for code that is more readable.

Thank you,

John

**Comment by mketchum** [comment]
Hi John,

We are happy to see that you are using and looking to extend the widget. This repo is the only version of the widget. We do have long term plans for doing some refactoring on this project to help with extensibility, but nothing concrete. If there are specific issues in extending the widget, we are happy to help.

Thanks!

**Comment by trijohn** [comment]
Thanks. My question was more around readability. It seems everything is abbreviated and maybe that is on purpose to control the code. In it current state I cannot work with it much as it would take hours to figure out. 

I am in the process of getting api support for the remember me adapter (Anthem is the company) and so it would be good to have that supported as well. 

On a second note, any plans on integrating with react-native? Would be good to have it working on mobile as well. 

Thanks. 

John
