### ISSUE TITLE
Change password is not asking current password for redirectless implementation

### ISSUE THREAD

**Issue by mechnixlab** [pingidentity/pf-authn-js-widget#53]
Redirectless implementation change password is not showing Existing password 

**To Reproduce**
1.  Setup initial
var authnWidget = new PfAuthnWidget("https://localhost", { divId: 'authnwidget' });
var config = {
  client_id: 'test',
  response_type: 'token id_token',
  onAuthorizationSuccess: function (response) {
    console.log(response);
  }
};
authnWidget.initRedirectless(config); 
2. After load Login screen click on change password'

![image](https://user-images.githubusercontent.com/54431232/107226303-23732080-6a44-11eb-85cc-eefae68809b8.png)

**Comment by sseenappa** [comment]
@mechnixlab Can you please confirm the version of PingFederate and authn widget?

**Comment by mechnixlab** [comment]
"@ping-identity/pf-authn-js-widget": "^1.3.0",

**Comment by mketchum** [comment]
This does work as intended on PingFederate 10.2 but looks like this current password does not show up for older versions of PingFederate.

We will look into getting this one fixed

**Comment by mketchum** [comment]
Thanks for reporting this one. We have created a tickte internally to track the changes needed to PingFederate's Authentication API for this one. 

As a workaround, upgrading your PingFederate deployment to 10.2 will solve the problem for now.
