### ISSUE TITLE
malformed widget box

### ISSUE THREAD

**Issue by trijohn** [pingidentity/pf-authn-js-widget#55]
Hello, i have setup the widget and during the "Ping One for Customers" MFA flow, it is trying to do an auto-enrollment. while it works, the the details in the box are a little skewed and I am wondering if that is normal or because maybe this is a newly introduced feature.  Please see the attached image for reference.

![image](https://user-images.githubusercontent.com/18177864/109195605-92908a80-774f-11eb-8b27-e0a7e045791c.png)

**Comment by jwong-ping** [comment]
@trijohn did you include the `main-styles.css`? It contains the styling for those two elements which are not displaying correctly in your screenshot.

**Comment by trijohn** [comment]
Yes, I am using main-styles.css

Is there a particular part of the file I should look for?

**Comment by mketchum** [comment]
@trijohn the following in main.scss is used to style those elements. Once compiled, they should show up in main-styles.css

```
.spinner--margin-bottom-small {
  margin-bottom: 35px;
}

.input--otp {
  width: 100%;
  max-width: 190px;
  margin: 0 auto;
}

.back-button {
  width: 30px;
  height: 30px;
  border-radius: 50%;
  padding: 5px;
  position: absolute;
  min-height: 0;
  top: 15px;
  left: 15px
}
```

**Comment by trijohn** [comment]
thanks. Yes my css contains that and I even installed the latest package.  I am seeing the below right before the OTP required and wondering that is somehow causing it fail not execute the remaining code?  I am not using captcha and am not loading the related JS.

registering events for: AUTHENTICATION_REQUIRED index.js:614:26
dispatching actionId: authenticate store.js:45:16
Object { id: "a62lj", pluginTypeId: "j_AGR1E__nc2USbRhZPMQQ", status: "OTP_REQUIRED", devices: (1) […], user: {…}, selectedDeviceRef: {…}, _links: {…}, **checkRecaptcha: undefined, daysToExpireMsg: undefined**, logo: "https://assets.pingone.com/ux/end-user/0.33.0/images/ping-logo.svg" }
store.js:46:21
notifying # of listeners: 1 store.js:201:16
registering events for: OTP_REQUIRED

**Comment by trijohn** [comment]
Hi, looking to see if there is further information I can get on this. 

Thank you, 

John

**Comment by mketchum** [comment]
Hi John, 

If that CSS is there and being included in your app then the styling should look correct. Can you try in an incognito window or clear the cache to make sure any old CSS is being used?

**Comment by trijohn** [comment]
I will test but did you see my others errors about captcha undefined ? Happens right before the display. I am not using captcha.

**Comment by trijohn** [comment]
Hi Mark, I am attaching a HAR file for your reference.  if you search from the bottom up for "undefined" you will see a 404 error and I am not sure where this is getting set but suspect it is influencing the call to the CSS details.
thanks.

John


    On Thursday, March 4, 2021, 10:29:51 AM PST, mketchum <notifications@github.com> wrote:  
 
 


Hi John,

If that CSS is there and being included in your app then the styling should look correct. Can you try in an incognito window or clear the cache to make sure any old CSS is being used?

**Comment by trijohn** [comment]
Hi Mark, one last comment that hopefully can clear things up.  The files I am using were copied to a linux server running Tomcat.  This is when i get the behavior.  When I run on my local system using nodejs and npm, the page displays correctly.
Is there is a requirement to compile it differently when running on different platforms?  Thanks for your time thus far.

**Comment by mketchum** [comment]
Hi John,

It doesn't look like the HAR file made it across to github. I don't suspect the undefined fields to be cause of the issue here. That should just mean those fields did not apply to your config/request.

Compiling and deploying is largely the same across different containers. For this error, you need to link to main-styles.css in your main page that initializes the widget and it needs to be available from tomcat. After running npm install you will see the main-styles.css compiled into the /dist directory. The instructions for that are laid out here: https://github.com/pingidentity/pf-authn-js-widget#adding-the-widget-to-an-application.

I suspect that the main-styles.css either does not have the correct path, or an older version is deployed to tomcat.

**Comment by trijohn** [comment]
Thanks. I will figure it out.
