### ISSUE TITLE
typescript @types required

### ISSUE THREAD

**Issue by gowthamrodda** [pingidentity/pf-authn-js-widget#59]
Im trying to implement widget into my angular application, but couldnt find respective @types declarations.
Could you please help ?

**Comment by mketchum** [comment]
We don't currently have any typescript definitions for the widget. Would this be required in your app? We can look to getting a ticket filed for a future release.

**Comment by mketchum** [comment]
We've created a ticket internally to get typescript definitions added. This will be included in a future release of the widget

**Comment by gowthamrodda** [comment]
Yes I need typescript definitions for this widget to use in my project. Thanks for adding to your list. Will be waiting for this.
@mketchum
