### ISSUE TITLE
Error on IE 11

### ISSUE THREAD

**Issue by tomnevillester** [pingidentity/pf-authn-js-widget#81]
**Describe the bug**
The application appears not to work on IE11. 

The flow Id cannot be found on IE 11. It appears related to the credentials web request attribute which I believe not to be IE11 compatible. 

I note that according to https://docs.pingidentity.com/bundle/pingfederate-103/page/elz1592262150859.html we should send the withCredentials attribute set to true. 

**To Reproduce**
Test the application in IE11 on Windows 10. 

**Screenshots**
![image](https://user-images.githubusercontent.com/46212431/123582507-451d4a80-d821-11eb-8af3-2e3384928ed1.png)

![image](https://user-images.githubusercontent.com/46212431/123582564-60885580-d821-11eb-8d61-ef66d68d99e8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser IE11
 - Version See attached screenshot

Kind regards,
Tom

**Comment by mketchum** [comment]
Hi @tomnevillester, Thanks for reporting this. Can you take a look in the developer console and see what if there is anything logged in the console? It would be good to see if the request to PingFederate failed for some reason as well.

I tested this out in IE11 on Windows 8.1 and Windows 10 and IE11 is working as expected in my environment

**Comment by tomnevillester** [comment]
Sorry, my mistake I was using a simulator for IE 11 and it was misbehaving. This works fine thanks as you've stated. I'll close the issue.
